name: Build, Lint, and Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install lint and test dependencies
      run: pip install -r requirements-dev.txt

    - name: Lint with pylint
      run: pylint --fail-under=8.0 app/

    - name: Build the docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag secure-python-app \
          --build-arg SSL_CERT="${{ secrets.SSL_CERT }}" \
          --build-arg SSL_KEY="${{ secrets.SSL_KEY }}"

    - name: Run the docker image
      run: |
          docker run \
            --name running-app \
            -d \
            -p 8443:443 \
            secure-python-app

    - name: Wait for app startup
      run: |
        sleep 5

    - name: Run tests
      run: pytest

    - name: Stop and remove the container
      if: always()
      run: docker stop running-app && docker rm running-app
